apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: standalone-request-logger
spec:
  template:
    metadata:
      annotations:
        #autoscaling.knative.dev/target: "2"
        # autoscaling.knative.dev/maxScale: "30"
    spec:
      containers:
       - image: docker.io/aliok/standalone-request-logger
         env:
         - name: LATENCY
           value: "0"
